import { test, expect } from '@playwright/test';

test('Patient Registration Form', async ({ page }) => {
  await page.goto('https://feujidemo.appiancloud.com/suite/sites/patient-onboarding/page/home');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('saigiridhar.rv@feuji.com');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('Sai@#54321');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'ONBOARD NEW PATIENT' }).click();
  await page.getByPlaceholder('Enter your Email Id').click();
  await page.getByPlaceholder('Enter your Email Id').fill('sampleTest@yopmail.com');
  await page.getByPlaceholder('Enter your Phone number').click();
  await page.getByPlaceholder('Enter your Phone number').fill('9876788960');
  await page.getByPlaceholder('Enter your first name').click();
  await page.getByPlaceholder('Enter your first name').fill('Sample');
  await page.getByPlaceholder('Enter your last name').click();
  await page.getByPlaceholder('Enter your last name').fill('Demo');
  await page.getByText('Male').first().click();
  await page.getByTestId('DatePickerWidget-calendarButton').first().click();
  await page.getByTestId('DatePicker-clearButton').click();
  await page.getByLabel('Date of Birth').click();
  await page.getByLabel('Date of Birth').fill('04/03/1993');
  await page.getByRole('listbox', { name: 'Marital StatusRequired asterisk' }).click();
  await page.getByText('Single').click();
  await page.getByPlaceholder('Enter your Driver License Number').click();
  await page.getByPlaceholder('Enter your Driver License Number').fill('MH-12-2009-0033020');
  await page.getByPlaceholder('Enter your Address').click();
  await page.getByPlaceholder('Enter your Address').fill('Inorbit MallHyder');
  await page.getByPlaceholder('Enter your City').click();
  await page.getByPlaceholder('Enter your City').fill('Hyderanad');
  await page.getByPlaceholder('Enter your state').click();
  await page.getByPlaceholder('Enter your state').fill('Tealngana');
  await page.getByPlaceholder('Please enter your postal code').click();
  await page.getByPlaceholder('Please enter your postal code').fill('500016');
  await page.getByPlaceholder(' Enter First name').click({
    modifiers: ['Shift']
  });
  await page.getByPlaceholder(' Enter First name').click();
  await page.getByPlaceholder(' Enter First name').fill('Sample TestD');
  await page.getByPlaceholder('Enter Last name').click();
  await page.getByPlaceholder('Enter Last name').fill('Demo');
  await page.getByPlaceholder('Enter Phone Number').click();
  await page.getByPlaceholder('Enter Phone Number').fill('7878654432');
  await page.getByRole('listbox', { name: 'Relationship to PatientRequired asterisk' }).click();
  await page.getByText('Uncle').click();
  await page.getByRole('listbox', { name: 'Mode of Request' }).click();
  await page.getByRole('option', { name: 'Phone' }).getByText('Phone').click();
  await page.getByRole('listbox', { name: 'Reason For visit' }).click();
  await page.getByText('Gout').click();
  await page.getByPlaceholder('Enter your Weight').click();
  await page.getByPlaceholder('Enter your Weight').fill('88');
  await page.getByRole('combobox', { name: 'Appointment DateRequired asterisk' }).click();
  await page.getByText('12:00 PM').click();
  await page.getByPlaceholder('Enter your Height').click();
  await page.getByRole('textbox', { name: 'Appointment DateRequired asterisk' }).click();
  await page.getByRole('textbox', { name: 'Appointment DateRequired asterisk' }).fill('08/05/2023');
  await page.getByPlaceholder('Enter your Height').click();
  await page.getByPlaceholder('Enter your Height').fill('511');
  await page.getByText('Yes').click();
  await page.getByLabel('Medication List').click();
  await page.getByLabel('Medication List').fill('Paracteamol');
  await page.getByRole('button', { name: 'Submit' }).click();
});
test('Updating patient Registration form', async ({ page }) => {
    await page.goto('https://feujidemo.appiancloud.com/suite/sites/patient-onboarding/page/home');
    await page.getByPlaceholder('Username').click();
    await page.getByPlaceholder('Username').fill('saigiridhar.rv@feuji.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('Sai@#54321');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.getByRole('link', { name: 'Doctor\'s Portal' }).click();
    await page.getByRole('link', { name: 'APPT-000081' }).click();
    await page.getByRole('button', { name: 'Update Appointment' }).click();
    await page.getByRole('listbox', { name: 'Mode of RequestRequired asterisk' }).click();
    await page.getByRole('option', { name: 'Phone' }).getByText('Phone').click();
    await page.getByLabel('Prescription').click();
    await page.getByLabel('Prescription').fill('dolo 650');
    await page.getByRole('button', { name: 'Submit' }).click();
  });
  test('Checking the metrices',async ({page}) => {
    await page.goto('https://feujidemo.appiancloud.com/suite/sites/patient-onboarding/page/metrics');
    await page.getByPlaceholder('Username').click();
    await page.getByPlaceholder('Username').fill('saigiridhar.rv@feuji.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('Sai@#54321');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.getByRole('link', { name: 'Metrics' }).click();
    await page.getByRole('application', { name: 'Timeline Chart' }).getByRole('button', { name: 'Show Appointments' }).click();
    await page.getByRole('button', { name: 'Show New Patients' }).click();
    await page.getByRole('application', { name: 'Timeline Chart' }).getByRole('button', { name: 'Show Appointments' }).click();
    await page.getByRole('button', { name: 'Show New Patients' }).click();
  }); 